version: "3.3"

volumes:
  pgdata:

services:
  app:
    container_name: snake-city
    build: .
    restart: always
    expose: 
      - 80
    ports: 
      - "80:80"
    networks: 
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`snake.city`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "10"    