version: "3.3"

networks:
  web:
    external: true

volumes:
  pgdata:

services:
  snakecity:
    container_name: snakecity
    build: .
    restart: always
    expose: 
      - 80
    networks: 
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.snakecity.rule=Host(`snake.city`)"
      - "traefik.http.routers.snakecity.entrypoints=websecure"
      - "traefik.http.routers.snakecity.tls.certresolver=myresolver"      
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "10"    